name: Unit Testing + Code Coverage

on: 
  push

defaults:
  run:
    working-directory: ./SortManager/SortManagerTests

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.15.2 -DirectDownload -OutputDirectory .
    - name: Run UnitTests
      run: dotnet test --logger:"console;verbosity=normal"
