name: Unit Testing

on: 
  push

defaults:
  run:
    working-directory: ./SortManager/

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run UnitTests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=lcov.info
    - name: coveralls      
      uses: coverallsapp/github-action@v1.1.1
      with:
      github-token: ${{secrets.GITHUB_TOKEN }} 
      path-to-lcov: SafariParkTests/lcov.info
